name: Build Debug APK

on:
  # 每次向主分支 push 代码时触发
  push:
    branches: [ main, master ]
  # 允许在 GitHub Actions 页面手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Java 环境 (Android 构建需要)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # 3. 授予 gradlew 执行权限
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      # 4. 使用 Gradle 构建 Debug 版本的 APK
      #    这会生成一个未签名的、用于调试的 APK 文件
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 5. 上传生成的 APK 文件作为产物
      #    你可以在工作流运行结束后下载这个文件
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Blinky-Debug-APK # 下载时的文件名
          path: app/build/outputs/apk/debug/app-debug.apk # APK 生成的路径 